#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
sudo touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
custom_header="add_header X-Served-By \$hostname;"
echo "$custom_header" >> /etc/nginx/nginx.conf
sudo service nginx restart
